steps:
  # build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/meal-wallet-authentication-svc', '.']
    # push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/meal-wallet-authentication-svc']
    # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['beta', 'run', 'deploy', 'meal-wallet-authentication-svc', '--image', 'gcr.io/$PROJECT_ID/meal-wallet-authentication-svc', '--region', 'europe-west2','--platform', 'managed', '--allow-unauthenticated' ,'--quiet']
    timeout: 1200s
images:
  - gcr.io/$PROJECT_ID/meal-wallet-authentication-svc
timeout: 1200s
